name:javaapp- cicd
on:
  workflow_dispatch
jobs:
  runs-on: ubuntu-latest
steps:
 - uses: actions/checkout@v2
 - name: setup jave
   uses: action/setup-java@v1
   with:
     java-version: 1.11

    cat java-version

 - name: Grant execute permission for gradlew
      run: chmod +x gradlew

 - name: Build with Gradle
      run: ./gradlew build
