name: javaapp-cicd
on:
  workflow_dispatch
jobs:
 build:
   runs-on: ubuntu-latest
 steps:
  - uses: actions/checkout@v2
  - name: setup java
    uses: action/setup-java@v1
    with:
    java-version: 11

      java-version

  - name: Grant execute permission for gradlew
     run: chmod +x gradlew

  - name: Build with Gradle
     run: ./gradlew build
