name: javaapp-cicd
on:
  workflow_dispatch:
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
      - uses: actions/checkout@v2
      - name: setup java
        uses: actions/setup-java@v1
        with:
           java-version: 11
      #java-version
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: awsdp
          password: D4deepth@1104
      - name: push image to hub 
        run:
          docker push awsdp/java-app:tagname

